apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  labels:
    app: ecommerce 
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: ecommerce 
  template:
    metadata:
      labels:
        app: ecommerce 
    spec:
      containers:
      - name: db 
        image: sreedocker123/phpmysqlecommmysql:updated 
        imagePullPolicy: Always
        ports:
        - containerPort: 3306 
